#define WIDTH 1024.0f
#define HEIGHT 576.0f

#define SHADOW_WIDTH (WIDTH * 2.0f)
#define SHADOW_HEIGHT (HEIGHT * 2.0f)

#define TILE_WIDTH  32.0f
#define TILE_HEIGHT 32.0f

#define MAX_LIGHT_RADIUS 350.0f
#define LIGHT_POWER 0.2f

#define NUM_X_TILES (WIDTH / TILE_WIDTH)
#define NUM_Y_TILES (HEIGHT / TILE_HEIGHT)

#define THREAD_GROUP_WIDTH 32
#define THREAD_GROUP_HEIGHT 32

#define NUM_TILES NUM_X_TILES * NUM_Y_TILES

#define LIGHTS_PER_X_PIXEL 32.0f
#define LIGHTS_PER_Y_PIXEL 32.0f

#define NUM_X_LIGHTS (SHADOW_WIDTH / LIGHTS_PER_X_PIXEL)
#define NUM_Y_LIGHTS (SHADOW_HEIGHT / LIGHTS_PER_Y_PIXEL)

#define NUM_LIGHTS NUM_X_LIGHTS * NUM_Y_LIGHTS

#define BLOOM_DIVISION 4.0f

#define COMPUTE_TILE_WIDTH 32
#define COMPUTE_TILE_HEIGHT 32

#define MAX_LIGHTS_PER_TILE (NUM_LIGHTS)